package com.dichoyhecho.dichoyhecho.enums;

public enum UserRole {
    NATIONAL_POLICE,
    MUNICIPAL_POLICE,
    TRAFFIC_POLICE,
    MUNICIPAL_FIREFIGHTER,
    VOLUNTEER_FIREFIGHTER,
    CONRED_AGENT,
    GUATEMALA_ARMY,
    PUBLIC_HEALTH_PERSONNEL,
    TRANSMETRO_MANAGER,
    ORNAMENT_PERSONNEL,
    MUNICIPAL_OFFICIAL,
    MUNICIPAL_JUDGE,
    RESIDENT
}
