package com.dichoyhecho.dichoyhecho.enums;

public enum UserRole {
    NATIONAL_CIVIL_POLICE,
    MUNICIPAL_POLICE,
    MUNICIPAL_TRAFFIC_POLICE,
    MUNICIPAL_FIRE_DEPARTMENT,
    VOLUNTEER_FIRE_DEPARTMENT,
    CONRED_AGENT,
    GUATEMALAN_ARMY,
    PUBLIC_HEALTH_PERSONNEL,
    TRANSMETRO_MANAGER,
    PUBLIC_MAINTENANCE_PERSONNEL,
    MUNICIPAL_AUTHORITY,
    MUNICIPAL_AFFAIRS_JUDGE,
    CITIZEN
}
