package com.dichoyhecho.dichoyhecho.enums;

public enum UsuarioRoles {
    POLICIA_NACIONAL_CIVIL,
    POLICIA_MUNICIPAL,
    POLICIA_MUNICIPAL_DE_TRANSITO,
    BOMBERO_MUNICIPAL,
    BOMBERO_VOLUNTARIO,
    AGENTE_CONRED,
    EJERCITO_DE_GUATEMALA,
    PERSONAL_DE_SALUD_PUBLICA,
    GESTOR_DE_TRANSMETRO,
    PERSONAL_DE_ORNATO,
    PERSONALIDAD_DE_MUNICIPALIDAD,
    JUEZ_DE_ASUNTOS_MUNICIPALES,
    VECINO
}
